OmnipreneurshipAcademy/edx-platform

- lms/envs/devstack.py
[LP-2343](https://philanthropyu.atlassian.net/browse/LP-2343)
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/1)
**Why did I enable it here?**
- We don't need to customize docker images.
- In this release edX recommends, to enable theme in devstack make changes in this file.
- edX has deprecated lms|cms.env.json files, and added .yml in production envs, in devstack I didn't find yml files, no documentation found.
> Enable ADG edx theme settings

- common/static/js/src/lang_edx.js
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/9)
Context:
- Whatever we use as the name of selector is being passed as data member to `i18n/setlang` API, previous implementation was sending `radio-select-language` as key which was not changing language at all.
- This is a bug in [LP-2341](https://philanthropyu.atlassian.net/browse/LP-2341), but was not captured, because in case you are not logged in this API is not used to setlang, that is totally a different mechanism and once you switched language in non logged in mode, it caches the the cookies and use them effectively. But whenever it would be tried after clearing cache, or on a new machine it will cause issue.
> Change selector to pass correct data in i18n/setlang

- common/djangoapps/student/views/management.py
- lms/djangoapps/instructor/enrollment.py
- lms/envs/devstack.py
- openedx/adg/common/lib/mandrill_client/client.py
- openedx/adg/lms/student/helpers.py
- openedx/adg/lms/utils/env_utils.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/core/djangoapps/user_authn/views/register.py
[LP-2418](https://philanthropyu.atlassian.net/browse/LP-2418)
Send out of the box edX emails using mandrill templates. edX uses edx-ace package to send these emails we are changing it mandrill and defining our own templates for that.
Following are the emails that are being send using mandrill as a result of this PR.
-     USER_ACCOUNT_ACTIVATION_TEMPLATE
-     PASSWORD_RESET_TEMPLATE
-     ENROLLMENT_CONFIRMATION_TEMPLATE
-     COURSE_ENROLLMENT_INVITATION
-     CHANGE_USER_EMAIL_ALERT 
-     VERIFY_CHANGE_USER_EMAIL
Following files are created/updated in this PR
**openedx/adg/lms/student/helpers.py:** This file contains functions that sends emails for all above described events
**common/djangoapps/student/views/management.py:** This is a core file which contains events for course …
> LP-2418 Send all OTB emails using mandrill templates

- openedx/adg/common/lib/mandrill_client/client.py
- openedx/adg/lms/student/helpers.py
Our course invitation email template **(COURSE_ENROLLMENT_INVITATION)** is changed, in this PR we have made changes to accommodate updated template
Files updated in this commit:
1. openedx/adg/lms/student/helpers.py: Code updated for course invitation email
2. openedx/adg/common/lib/mandrill_client/client.py: Template Id updated
> LP-2456 Send updated course invitation email

- lms/urls.py
- openedx/adg/lms/applications/api_urls.py
- openedx/adg/lms/applications/api_views.py
- openedx/adg/lms/applications/serializers.py
- openedx/adg/lms/applications/test/factories.py
- openedx/adg/lms/applications/test/test_api_views.py
- openedx/adg/lms/applications/test/test_helpers.py
- openedx/adg/lms/applications/test/test_serializers.py
- openedx/adg/lms/urls.py
Unit test for education and work experience apis related to [LP-2460](https://philanthropyu.atlassian.net/browse/LP-2489)
Tests related code are in **openedx/adg/lms/applications/test/** directory
Few changes in this commit related to education and work experience apis and not related to tests. Those are the suggestions from @ahmed-faraz46 from following PRs.
- Add swagger documentation for education and work experience apis, [PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/86)
- Write Required APIs for application page 2, [PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/88
)
> LP-2489 Unit tests for education and work experience apis

- lms/envs/test.py
[LP-2500](https://philanthropyu.atlassian.net/browse/LP-2500)
Tests were failing as we have updated the languages and we only have support for english and arabic. I have over-ridden settings to add all the languages for tests.
> LP-2500 fixed tests for language configs

- openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py
[LP-2493](https://philanthropyu.atlassian.net/browse/LP-2493) Adding exit code for successful termination in command `update_is_prerequisite_courses_passed`
> LP-2493 Adding exit code for successful termination in command 

- .github/workflows/quality.yml
After koa-upgrade, edx-lint version has been upgraded too from 1.4.1 to 1.5.2. In this version **score = no** has been added in Report setting mentioned in file **pylintrc**
> lp-2518 fix pylint configuration

- openedx/adg/common/lib/mandrill_client/client.py
- openedx/adg/lms/helpers.py
- openedx/adg/lms/tests/__init__.py
- openedx/adg/lms/tests/constants.py
- openedx/adg/lms/tests/test_helpers.py
A fix in [LP-2479](https://philanthropyu.atlassian.net/browse/LP-2479), [LP-2565](https://philanthropyu.atlassian.net/browse/LP-2565)
- Rename accepted email template slug
- Add unit tests for lms helpers
> Fix get_user_first_name by getting name instead of full_name

- openedx/adg/lms/applications/api_views.py
- openedx/adg/lms/applications/helpers.py
- openedx/adg/lms/applications/tests/test_helpers.py
[LP-2478](https://philanthropyu.atlassian.net/browse/LP-2478)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/138)
- Update education and work experience APIs to validate that user should not be able to select future dates.
- I also allow put method to resolve a bug in APIs to update education and experience records
> LP-2478 Dont allow future dates in education and experience API

- lms/djangoapps/branding/views.py
Core change has been done in this commit, Upon hitting the root url, authenticated user was redirected to dashboard and unauthenticated user to home page/marketing page. If we were to override the view performing the above task to only redirect to marketing page, still we would have to make core change in url.py to point to this new view, plus the current view would become a dead piece of code which would never be reached. Hence, after consulting @ahmed-faraz46 it was decided to remove lines 38 to 47 which redirects authenticated user to dashboard.
> LP-2588 Redirection and Textual Issues on ADG Platform

- .github/workflows/quality.yml
[LP-2585](https://philanthropyu.atlassian.net/browse/LP-2585)
- Export philu personal access token in environment
NOTE: For CircleCI workflow, PHILU_PAT is exported in environment, from the app, so no code change was required, Right now pipelines might post that no python file detected, but I've tested it with some temporary changes and reverted those changes, attaching screen shots of successful runs
> LP-2585 Export philu personal access token in environment

- openedx/adg/lms/applications/forms.py
- openedx/adg/lms/applications/tests/constants.py
- openedx/adg/lms/applications/tests/test_forms.py
[LP-2579](https://philanthropyu.atlassian.net/browse/LP-2579)
- Integrate error banner
- Add validations for saudi_national and birthdate in the backend and the frontend
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/186)
> LP-2579 -  Display error message if user is unqualified for written application

- openedx/adg/lms/branding_extension/helpers.py
- openedx/adg/lms/branding_extension/tests/helpers_tests.py
[LP-2603](https://philanthropyu.atlassian.net/browse/LP-2603)
Previously contact in the footer was linked to a support link, as we have a different requirement for static contact page, so we have change the link accordingly.
> Change contact url to /contact

- openedx/adg/common/lib/mandrill_client/client.py
- openedx/adg/common/lib/mandrill_client/email_data.py
- openedx/adg/common/lib/mandrill_client/tasks.py
- openedx/adg/common/lib/mandrill_client/tests/test_tasks.py
- openedx/adg/lms/applications/admin.py
- openedx/adg/lms/applications/helpers.py
- openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py
- openedx/adg/lms/student/helpers.py
- openedx/adg/lms/student/tests/test_helpers.py
[LP-2630](https://philanthropyu.atlassian.net/browse/LP-2630)
- Add mandrill support for a group of email addresses to send the email to.
- Change all the occurrences of the send email task to conform with the new changes.
> LP-2630 - Add mandrill support for multiple emails

- openedx/adg/lms/webinars/admin.py
[LP-2629](https://philanthropyu.atlassian.net/browse/LP-2629)
[adg-theme-PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/206)
Notes:
- Update presenter, co-hosts and panelists fields for model admin i.e. use raw_id_fields.
- Save as new button text is changed to Clone  for webinars
- Handle status of a webinar. Status should be marked as upcoming for cloned webinars.
> LP-2629 Customise interface for webinar for admins

- openedx/adg/lms/webinars/helpers.py
- openedx/adg/lms/webinars/models.py
- openedx/adg/lms/webinars/tests/test_helpers.py
[LP-2617](https://philanthropyu.atlassian.net/browse/LP-2617)
- Send emails to the presenter, panelists, and co-hosts in addition to the registered users.
- Make sure an email address gets only a single email per cancellation.
- Add/Modify unit tests to cover all the edge cases.
> LP-2617 - Send cancellation emails for cohosts, panelists and presenter

- openedx/adg/lms/applications/helpers.py
- openedx/adg/lms/applications/models.py
- openedx/adg/lms/applications/tests/test_helpers.py
- openedx/adg/lms/applications/tests/test_models.py
[LP-2649](https://philanthropyu.atlassian.net/browse/LP-2649)
- Display a dropdown option  for `adg-admin` page if the logged in user is an ADG Admin or a Business Line Admin, or a Superuser.
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/224)
> LP-2649 - Add ADG Admin link in profile dropdown for admin users

- openedx/adg/lms/branding_extension/__init__.py
- openedx/adg/lms/courseware_override/__init__.py
- openedx/adg/lms/our_team/__init__.py
**[LP-2673](https://philanthropyu.atlassian.net/browse/LP-2673)** Tech doc for branding_extension, courseware_override & out_team apps
Note: Tech doc for course_meta is already covered in this [PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/289)
> LP-2673 Tech doc for branding_extension, courseware_override & out_team apps

- openedx/adg/lms/webinars/admin.py
- openedx/adg/lms/webinars/tests/test_admin.py
- fix for allowing user to change the webinar status to canceled
> LP-2698 webinar registration delete permission from admin

- openedx/adg/lms/applications/tests/test_views.py
- openedx/adg/lms/applications/urls.py
- openedx/adg/lms/applications/views.py
- Add view and url for Application Introduction View
- Changed the urls for introduction and hub to `application/` and `application/progress/` respectively
- User is only allowed to visit Application Introduction page when the user is authenticated and the user has not clicked the `Start Application` button on the Application Introduction page prior to that point. Once the Introduction page's `Start Application` button has been pressed by the user, an ApplicationHub object is created for that particular user and from that point onward that user is redirected to the Application Hub page whenever they try to land on the Introduction page.
> LP-2699 - Add urls and view for Application Introduction view

- lms/envs/common.py
- openedx/adg/lms/branding_extension/constants.py
- openedx/adg/lms/branding_extension/helpers.py
- openedx/adg/lms/branding_extension/tests/helpers_tests.py
- Add ADG zendesk support link in settings
- Append that link in navigation links
- Reorder links as per the new desings
- Add curtom href target support in footer navigation links
NOTE: I've added target blank in support url as it is a best practice to open up all third parties in a new tab, otherwise there are always some chances that users will lose track. For transparency with product, I've added an agenda in biweekly standup.
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/299)
> LP-2697 Add support link in footer

- openedx/adg/lms/applications/admin.py
- openedx/adg/lms/applications/constants.py
- openedx/adg/lms/applications/helpers.py
- openedx/adg/lms/applications/models.py
- openedx/adg/lms/applications/tests/constants.py
- openedx/adg/lms/applications/tests/factories.py
- openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py
- openedx/adg/lms/applications/tests/test_helpers.py
- openedx/adg/lms/applications/tests/test_models.py
[LP-2719](https://philanthropyu.atlassian.net/browse/LP-2719)
- Add `hear_about_omni` field in the Application Info fieldset
- Add a fieldset for `Interest in Program` and `Background Question` fields
- Add references section by creating an inline for `references` similar to Education & Experience
- Add course scores for both program and BU prereq courses in the prerequisites (scores) fieldset
- Only allow an admin to submit an application when all the prereq courses have been cleared i.e program prereqs and business_line prereqs
> LP-2719 - Update admin application review page

- openedx/adg/lms/helpers.py
- openedx/adg/lms/webinars/constants.py
- openedx/adg/lms/webinars/forms.py
- openedx/adg/lms/webinars/helpers.py
- openedx/adg/lms/webinars/models.py
[LP-2721](https://philanthropyu.atlassian.net/browse/LP-2721)
- Used UTC time for scheduling the emails.
- For now I have added a help text for the admins that the time they are adding is in UTC. We will incorporate the 2nd expected result in phase 2, in which we will create dedicated dashboard for admins.
> LP-2721 Fix timezone for webinar reminder emails

- lms/static/js/student_account/views/RegisterView.js
[Inconsistent Behaviour of Validation Messages on Registration Page](https://philanthropyu.atlassian.net/browse/LP-2753)
We were sending field validation for all fields even if we don't have data of that field in front-end.
So here I've added a check to send only those fields to validate which have some data.
> LP-2753 Inconsistent Behaviour of Validation Messages on Registration Page

- openedx/adg/lms/applications/helpers.py
- openedx/adg/lms/applications/tests/test_helpers.py
- openedx/adg/lms/applications/tests/test_views.py
- openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2754) 
[Bug](https://philanthropyu.atlassian.net/browse/LP-2754)
At first we were sending email of application submission through command. Now that the application hub flags are updating in the view we also need to send email of submission when the user completes all the steps. Following code changes were made to accommodate that.
> LP-2754 update view to send email

- lms/static/js/student_account/views/RegisterView.js
Reverts OmnipreneurshipAcademy/edx-platform#415
Reason: We don't need this change. Because its an OpenEdx issue which I think, they have resolved in their latest master branch. 
This issue was mainly reported because Automation test cases were failing after few hits to API, the reason is we have set the RateLimit = 30 hits per week (30/7d) for Registration API, And after 30 hits it throws 403 forbidden error. So that is the main issue which should be resolved. I've created separate [ticket](https://philanthropyu.atlassian.net/jira/software/projects/DDO/boards/10?selectedIssue=DDO-64) for this
> Revert "LP-2753 Inconsistent Behaviour of Validation Messages on Registration Page"

- requirements/edx/testing.txt
[LP-2766](https://philanthropyu.atlassian.net/browse/LP-2766)
To make updates in ORA2, we forked it and made changes in it. Due to these changes core unit test started failing. 
I have updated to install the parent ORA2 xblock from edX as it was previously for the tests. We did the same for `msp-assessment` xblock.
> LP-2766 Use ORA2 Xblock by edX for testing
