OmnipreneurshipAcademy/edx-platform

common/static/js/src/lang_edx.js
[LP-2341](https://philanthropyu.atlassian.net/browse/LP-2341)
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/3)
Added radio button selectors in default language selectors to make sure it doesn't break any edX's page.
=> Change language switcher to support radio buttons

.github/workflows/quality.yml, philu_actions/scripts/dependency_downloader.sh
[LP-2415](https://philanthropyu.atlassian.net/browse/LP-2415) Implementing Github actions for linting
=> LP-2415 Implementing Github actions for linting

common/djangoapps/student/views/management.py, lms/djangoapps/instructor/enrollment.py, lms/envs/devstack.py, openedx/adg/common/lib/mandrill_client/client.py, openedx/adg/lms/student/helpers.py, openedx/adg/lms/utils/env_utils.py, openedx/core/djangoapps/user_authn/views/password_reset.py, openedx/core/djangoapps/user_authn/views/register.py
Merging in develop again, as I just refreshed develop from master.
=> LP-2418 Send all OTB emails using mandrill templates

openedx/adg/lms/registration_extension/forms.py
[LP-2439](https://philanthropyu.atlassian.net/browse/LP-2439)
Updated placeholder for a field
=> LP-2439 updated placeholder

lms/envs/common.py
constant for CDN link has been set in lms/envs/common.py file
Adjacent pull request in adg-edx-theme
[24](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/24)
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2347)
=> LP-2347 ADG header integrated

openedx/adg/lms/student/tests/test_helpers.py, openedx/adg/lms/utils/tests/test_env_utils.py, requirements/adg/base.txt
[LP-2459](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/54) Unit test for edX OTB emails in student and utils app
=> LP-2459 Unit test for edX OTB emails in student and utils app

lms/envs/common.py, openedx/adg/lms/branding_extension/helpers.py, openedx/adg/lms/branding_extension/tests/helpers_tests.py
- Mark all unavailable links as None in MKTG_URL_LINK_MAP
- Add branding extension
- Add helper to get ADG footer navigation links
=> LP-2469 Modify footer navigation links

openedx/adg/common/mailchimp_pipeline/client.py, openedx/adg/common/mailchimp_pipeline/handlers.py, openedx/adg/common/mailchimp_pipeline/helpers.py, openedx/adg/common/mailchimp_pipeline/tasks.py, openedx/adg/common/mailchimp_pipeline/tests/test_handlers.py, openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py, openedx/adg/common/mailchimp_pipeline/tests/test_tasks.py, openedx/adg/lms/applications/test/factories.py, openedx/adg/lms/registration_extension/tests/factories.py
[LP-2446](https://philanthropyu.atlassian.net/browse/LP-2446)
=> LP-2446 sync user data with mailchimp

openedx/adg/lms/applications/management/commands/tests/test_update_is_prerequisite_courses_passed.py, openedx/adg/lms/applications/test/factories.py
**test_update_is_prerequisite_courses_passed.py**. added which contains tests for management command
Here is the [Ticket LP-2458](https://philanthropyu.atlassian.net/browse/LP-2458)
=> LP-2458 Unit tests for update_is_prerequisite_courses_passed command added

openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/test/test_models.py
- Change model method to cater changes in progress percentage sent
- Update tests associated to changed model
Previous [PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/59) for LP-2461
Previous [PR for design](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/49) of LP-2461
[PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/57) for design fix of LP-2461
=> LP-2461 - Integrate Application Hub Page (Adding design fixes)

openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/test/constants.py, openedx/adg/lms/applications/test/test_views.py, openedx/adg/lms/applications/urls.py, openedx/adg/lms/applications/views.py
**urls.py** has been modified
**views.py** has been modified by adding a new class view
[Ticket LP-2378](https://philanthropyu.atlassian.net/browse/LP-2378)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/76)
=> LP-2378 Backend implementation of user application cover letter page

openedx/adg/lms/applications/test/constants.py, openedx/adg/lms/applications/test/test_views.py, openedx/adg/lms/applications/views.py
[adg-edx-theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/83)
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2378)
[Reported Bugs](https://philanthropyu.atlassian.net/browse/LP-2496)
=> LP-2378 [Fix bugs] Backend implementation of user application cover letter page

openedx/adg/lms/applications/test/constants.py, openedx/adg/lms/applications/test/test_views.py, openedx/adg/lms/applications/urls.py, openedx/adg/lms/applications/views.py
[adg-edx-theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/89)
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2378)
[Reported Bugs](https://philanthropyu.atlassian.net/browse/LP-2496)
=> LP-2378 [Updated] Backend implementation of user application cover letter page

openedx/adg/lms/applications/test/test_views.py, openedx/adg/lms/applications/views.py
Business Line was being selected during sign-up hence when user opened cover letter, it should had been pre-filled.
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2378)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/93)
=> LP-2378 Pre-fill Business Line selected during Signup

.github/workflows/generate_translations.yml
Ticket: [LP-2473](https://philanthropyu.atlassian.net/browse/LP-2473)
Create github action to automate the translations flow by doing the following:
1. Install all dependencies.
2. Clone `adg-edx-theme` inside the repo in the _themes_ directory.
3. Checkout the feature branch in both the repos i.e `edx-platform` and `adg-edx-theme`.
4. Generate all the translations as described [here](https://github.com/OmnipreneurshipAcademy/devstack/blob/master/docs/adg/transifex_translations.rst).
5. Commit and push the changed translation files in the feature branch.
6. Push the changed translations to Transifex by `tx push` command.
=> LP-2473 - Create GitHub actions to automate translations flow

.github/workflows/generate_translations.yml
Ticket: [LP-2473](https://philanthropyu.atlassian.net/browse/LP-2473)
Create github action to automate the translations flow by doing the following:
1. Install all dependencies.
2. Clone adg-edx-theme inside the repo in the themes directory.
3. Checkout the feature branch in both the repos i.e edx-platform and adg-edx-theme.
4. Generate all the translations as described [here](https://github.com/OmnipreneurshipAcademy/devstack/blob/master/docs/adg/transifex_translations.rst).
5. Commit and push the changed translation files in the feature branch.
6. Push the changed translations to Transifex by tx push command.
=> LP-2473 - Add github workflow to automate translation flow.

openedx/adg/lms/applications/constants.py, openedx/adg/lms/applications/forms.py, openedx/adg/lms/applications/tests/constants.py, openedx/adg/lms/applications/tests/test_forms.py, openedx/adg/lms/applications/tests/test_helpers.py, openedx/adg/lms/applications/tests/test_views.py, openedx/adg/lms/applications/urls.py, openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2378)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/113)
=> LP-2378 Backend implementation of user application cover letter page (resolve conflicts)

openedx/adg/lms/static/components/student_account/PasswordResetConfirmation.jsx
Ticket: [LP-2531](https://philanthropyu.atlassian.net/browse/LP-2531)
- Added **aqua-blue** and **form-submit-btn** classes in 'Change Password' button in 'Password reset page'
=> LP-2531: added classes in Submit button in Password Reset Page

lms/static/js/student_account/views/LoginView.js
[LP-2562](https://philanthropyu.atlassian.net/browse/LP-2562)
- Change the message that is displayed on _Forget password_ email submission
=> LP-2562 - Change email reset message

.circleci/config.yml, .github/workflows/generate_translations.yml, .github/workflows/quality.yml
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2570)
=> LP-2570 Upgrade the python version being used in all of our pipelines

lms/envs/common.py
This PR was already merged in develop. As we have recreated develop due to a migration issue, We need to merge this again.
Link to the [old PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/182).
=> LP-2566 Update CDN Link

openedx/adg/common/lib/mandrill_client/client.py, openedx/adg/common/lib/mandrill_client/tasks.py, openedx/adg/common/lib/mandrill_client/tests/test_tasks.py, openedx/adg/lms/applications/admin.py, openedx/adg/lms/applications/helpers.py, openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py, openedx/adg/lms/applications/tests/test_helpers.py, openedx/adg/lms/student/helpers.py, openedx/adg/lms/student/tests/test_helpers.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2576)
=> LP-2576 Make mandrill client asynchronous

lms/djangoapps/courseware/views/views.py, openedx/adg/lms/applications/constants.py, openedx/adg/lms/applications/helpers.py, openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py, openedx/adg/lms/applications/managers.py, openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/tests/conftest.py, openedx/adg/lms/applications/tests/test_helpers.py, openedx/adg/lms/applications/tests/test_models.py, openedx/adg/lms/applications/views.py, openedx/adg/lms/conftest.py, openedx/adg/lms/courseware_override/__init__.py, openedx/adg/lms/courseware_override/helpers.py, openedx/adg/lms/student/helpers.py, openedx/adg/lms/student/tests/test_helpers.py
[LP-2523](https://philanthropyu.atlassian.net/browse/LP-2523)
Refactored Course Group Implementation
Update view for course catalog to display courses using Course Groups
**Note:** Please ignore the linting errors. Those are related to the core code.
=> LP-2523 Filter Courses on Course Catalog

openedx/adg/common/installed_apps.py, openedx/adg/lms/urls.py, requirements/adg/base.txt, setup.py
[LP-2574](https://philanthropyu.atlassian.net/browse/LP-2574)
=> LP-2574 Integrate MSP assessment XBlock with ADG

requirements/adg/base.txt
[LP-2574](https://philanthropyu.atlassian.net/browse/LP-2574) postfix
For details, check out comments on [DDO-31](https://philanthropyu.atlassian.net/browse/DDO-31)
=> LP-2574 Add username in msp installation command

openedx/adg/lms/applications/managers.py, openedx/adg/lms/applications/tests/test_models.py, openedx/adg/lms/courseware_override/helpers.py, openedx/adg/lms/courseware_override/tests/constants.py, openedx/adg/lms/courseware_override/tests/test_helpers.py
- Queryset method to fetch MultilingualCourse via course_id safely
[Previous PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/196)
=> LP-2501 - Integrate course about page

openedx/adg/common/installed_apps.py, openedx/adg/lms/urls.py, requirements/adg/base.txt, setup.py
[LP-2574](https://philanthropyu.atlassian.net/browse/LP-2574)
=> LP-2574 Integrate MSP assessment XBlock with ADG #192

openedx/adg/lms/branding_extension/api.py, openedx/adg/lms/branding_extension/tests/test_api.py, openedx/adg/lms/registration_extension/constants.py, openedx/adg/lms/registration_extension/forms.py, openedx/adg/lms/user_authn_override/password_reset.py, openedx/adg/lms/user_authn_override/tests/test_password_reset.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2588)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/170)
=> LP-2588 Redirection and Textual Issues on ADG Platform

openedx/adg/common/lib/mandrill_client/client.py, openedx/adg/common/lib/mandrill_client/helpers.py, openedx/adg/common/lib/mandrill_client/tests/test_helpers.py
=> LP-2455 Add support for multilingual email template

.github/workflows/quality.yml, requirements/adg/base.txt
[LP-2595](https://philanthropyu.atlassian.net/browse/LP-2595)
Updated requirements file to install specific version of msp xblock.
Updated quality action to export branch of msp xblock as environment variable.
=> LP-2595 update requirements to install specific version of msp xblock

openedx/adg/lms/applications/forms.py, openedx/adg/lms/applications/tests/constants.py, openedx/adg/lms/applications/tests/test_forms.py
[LP-2579
](https://philanthropyu.atlassian.net/browse/LP-2579)
- Integrate error banner
- Add validations for saudi_national and birthdate in the backend and the frontend
[theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/183)
=> LP-2579 - Display error message if user is unqualified for written application

openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/tests/test_models.py, openedx/adg/lms/applications/views.py
[LP-2581](https://philanthropyu.atlassian.net/browse/LP-2581)
=> LP-2581 Add is education experience completed flag in context

requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
[LP-2613](https://philanthropyu.atlassian.net/browse/LP-2613) Fix requirements for py2neo
=> LP-2613 Fix requirements for py2neo

openedx/adg/lms/urls.py, openedx/adg/lms/webinars/urls.py, openedx/adg/lms/webinars/views.py
**Summary:** 
Temporary view URL for rendering templates. 
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/207)
=> LP-2616 Created template for webinar description page

openedx/adg/lms/webinars/tests/test_views.py, openedx/adg/lms/webinars/urls.py, openedx/adg/lms/webinars/views.py
[LP-2624](https://philanthropyu.atlassian.net/browse/LP-2624)
[adg-theme-PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/231)
Note: 
Integrate webinar description design
=> LP-2624 webinar description page

.github/workflows/quality.yml, requirements/adg/base.txt, requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2611)
[edx-ora2 PR](https://github.com/OmnipreneurshipAcademy/edx-ora2/pull/1)
=> LP-2611 Move PhilU ORA tables functionality in ADG

openedx/adg/lms/webinars/templatetags/custom.py
[LP-2626](https://philanthropyu.atlassian.net/browse/LP-2626)
Show confirm dialog box upon webinar creation/updation
[adg-edx-theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/235)
=> LP-2626 Show confirm dialog box for webinar

lms/envs/common.py, openedx/adg/lms/branding_extension/helpers.py, openedx/adg/lms/branding_extension/tests/helpers_tests.py, openedx/adg/lms/our_team/tests/test_views.py, openedx/adg/lms/our_team/urls.py, openedx/adg/lms/our_team/views.py, openedx/adg/lms/urls.py
[LP-2627
](https://philanthropyu.atlassian.net/browse/LP-2627)
- Remove our team page from static pages as it doesn't cater dynamic content
- Register a url in our_team app
- Add a view for our_team page
- Fix footer link for `our_team`
- Fix unit tests
[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/238)
=> LP-2627 - Add view and register url for our team page

openedx/adg/lms/webinars/__init__.py
Ticket: [LP-2676](https://philanthropyu.atlassian.net/browse/LP-2676)
=> LP-2676 Write technical documentation for webinars app

conf/locale/ar/LC_MESSAGES/django.po, conf/locale/ar/LC_MESSAGES/djangojs.po, openedx/adg/lms/branding_extension/__init__.py, openedx/adg/lms/courseware_override/__init__.py, openedx/adg/lms/our_team/__init__.py
**[LP-2673](https://philanthropyu.atlassian.net/browse/LP-2673)** Tech doc for branding_extension, courseware_override & our_team apps
Note: Tech doc for course_meta is already covered in this [PR](https://github.com/OmnipreneurshipAcademy/edx-platform/pull/289)
=> LP-2673 Tech doc for branding_extension, courseware_override & our_team apps

openedx/adg/cms/__init__.py, openedx/adg/common/__init__.py, openedx/adg/common/course_meta/__init__.py, openedx/adg/common/lib/mandrill_client/__init__.py, openedx/adg/common/mailchimp_pipeline/__init__.py, openedx/adg/lms/__init__.py, openedx/adg/lms/applications/__init__.py
[LP-2671](https://philanthropyu.atlassian.net/browse/LP-2671) ADG technical documentation for mailchimp_pipeline and mandrill_client app
[LP-2672](https://philanthropyu.atlassian.net/browse/LP-2672) ADG technical documentation for application app
=> LP-2671 LP-2672 Technical documentation for common and cms and applications

openedx/adg/lms/user_authn_override/__init__.py, openedx/adg/lms/user_authn_override/tests/__init__.py, openedx/adg/lms/utils/__init__.py, openedx/adg/lms/utils/tests/__init__.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2675)
=> LP-2675 ADG technical documentation for user_authn_override and utils apps

openedx/adg/lms/webinars/admin.py, openedx/adg/lms/webinars/tests/test_admin.py
Revoke webinar registration delete permission from ADG admin
=> LP-2698 Revoke webinar registration delete permission from ADG admin

openedx/adg/lms/applications/forms.py, openedx/adg/lms/applications/tests/test_forms.py
[LP-2692](https://philanthropyu.atlassian.net/browse/LP-2692)
Previous PR: #336
=> LP-2692 - Add validation error to a single field to improve UI

openedx/adg/lms/applications/admin.py, openedx/adg/lms/applications/managers.py, openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py, openedx/adg/lms/applications/tests/test_models.py, openedx/adg/lms/applications/tests/test_views.py, openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2702)
=> LP-2702 change application view/assess process for admin

openedx/adg/lms/applications/admin.py, openedx/adg/lms/applications/managers.py, openedx/adg/lms/applications/models.py, openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py, openedx/adg/lms/applications/tests/test_models.py, openedx/adg/lms/applications/tests/test_views.py, openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2702)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/289)
=> LP-2702 Written application should be available for admins as soon as learners have completed it

openedx/adg/lms/courseware_override/helpers.py, openedx/adg/lms/courseware_override/tests/test_helpers.py
Enable edX pre reqs courses and integrate pre reqs on course about page
[adg-edx-theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/300)
=> LP-2710 Enable edX pre reqs courses and integrate pre reqs on course about page

openedx/core/djangoapps/user_authn/views/login_form.py
[LP-2688](https://philanthropyu.atlassian.net/browse/LP-2688)
Back porting [a commit](https://github.com/edx/edx-platform/pull/27231/commits) from open edX, which is added to fix exactly the same issue we are facing.
NOTE: Overall there were some unit tests changed in [the PR](https://github.com/edx/edx-platform/pull/27231) in which this commit got merged. But no unit tests were added or updated for the particular change, we have back ported. So rest of the changes would be pulled with next upgrade. Moreover I've verified that the unit tests of user_authn app are running successfully with this change.
=> Backport, fix: Reduce safe-sessions false alarms.

openedx/adg/lms/applications/constants.py, openedx/adg/lms/applications/helpers.py, openedx/adg/lms/applications/rules.py, openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py, openedx/adg/lms/applications/tests/test_helpers.py
- Add references to the permission rules for BU admins
- Make course score section headings translatable
- Update unit tests
=> [POSTFIX] LP-2719 - Update Admin Application review

openedx/adg/lms/applications/admin.py
- Change the title of the field to make it consistent with the frontend
=> [POSTFIX] LP-2719 - Change field title for hear_about_omni in the backend

openedx/adg/common/lib/mandrill_client/client.py, openedx/adg/lms/student/helpers.py, openedx/adg/lms/student/tests/test_helpers.py, openedx/core/djangoapps/user_authn/views/password_reset.py
[Ticket: LP-2744](https://philanthropyu.atlassian.net/browse/LP-2744)
=> LP-2744 - Send adg password change success email

openedx/adg/lms/applications/helpers.py, openedx/adg/lms/applications/tests/test_helpers.py, openedx/adg/lms/applications/tests/test_views.py, openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2754)
[adg-edx-theme](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/347)
=> LP-2754 Make the instructions of omnipreneurship courses dynamic and change the flags incase all the courses are passed

openedx/adg/lms/applications/views.py
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2772)
=> LP-2754 Functional issues on 'Application hubs' model and 'Applications' (adg-admin) model

openedx/core/djangoapps/user_authn/views/login.py
[Ticket ](https://philanthropyu.atlassian.net/browse/LP-2773)
=> LP-2773 Reset Password Link redirects user to Page Not Found error 
